drop database livraria;
CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE  TABLE LIVRO(
	id_LIVRO              INTEGER               NOT NULL      PRIMARY KEY AUTO_INCREMENT,
	id_EDITORA            INTEGER               NOT NULL,    
	id_AUTOR              INTEGER 	            NOT NULL,   
	id_GENERO             INTEGER               NOT NULL,  
        TITULO		      VARCHAR(1000)	    NOT NULL,
	ANO_PUBLICACAO        CHAR(10)              NOT NULL,
	VALOR                 VARCHAR(10)           NOT NULL);

CREATE TABLE GENERO_LIVRO(
 	id_LIVRO             INTEGER 	 NOT NULL  		PRIMARY KEY AUTO_INCREMENT,
	id_GENERO            INTEGER  	 NOT NULL);

CREATE TABLE GENERO(
	id_GENERO         INTEGER             NOT NULL   	PRIMARY KEY AUTO_INCREMENT,
	NOME_GENERO       VARCHAR(200)        NOT NULL );

CREATE TABLE AUTOR_LIVRO(
	id_AUTOR       INTEGER		    NOT NULL, 
	id_LIVRO       INTEGER 	            NOT NULL);

CREATE TABLE AUTOR(
	id_AUTOR      INTEGER      	    NOT NULL  		PRIMARY KEY AUTO_INCREMENT,
	NOME          VARCHAR(200)          NOT NULL);
 
CREATE TABLE EDITORA(
	id_EDITORA     INTEGER         NOT NULL 		PRIMARY KEY AUTO_INCREMENT,
	NOME           VARCHAR(200)    NOT NULL);

CREATE TABLE ESTOQUE_LIVRO(
	id_ESTOQUE            INTEGER  	    NOT NULL,
	id_LIVRO              INTEGER       NOT NULL);

CREATE TABLE ESTOQUE(
	id_ESTOQUE     	        INTEGER         	NOT NULL        PRIMARY KEY AUTO_INCREMENT,
	id_LIVRO            	INTEGER  	  	NOT NULL,
	QUANTIDADE_LIVRO   	VARCHAR (100)   	NOT  NULL);

CREATE TABLE VENDA(
	ID_VENDA            INTEGER   	 	NOT NULL  		PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE          INTEGER   	 	NOT NULL,
	ID_VENDEDOR         INTEGER     	NOT NULL,
	VALOR_TOTAL         VARCHAR(10)   	NOT NULL,
	DATA_DE_VENDA	    CHAR(10) 		NOT NULL,
	QUANTIDADE          VARCHAR(200)  	NOT NULL);

CREATE TABLE CLIENTE(
       ID_CLIENTE     	        INTEGER  		NOT NULL     	PRIMARY KEY AUTO_INCREMENT,          
       NOME              	VARCHAR(200) 		NOT NULL,
       NUMERO                   VARCHAR(15)  		NOT NULL,
       GMAIL             	VARCHAR(200)  		NOT NULL,
       ANIVERSARIO              CHAR(10)  		NOT NULL,
       CPF                      CHAR(14)     		NOT NULL,
       ENDERECO              	VARCHAR(200)  		NOT NULL);

CREATE TABLE VENDEDOR(
       ID_VENDEDOR            INTEGER            NOT NULL	 PRIMARY KEY AUTO_INCREMENT,
       NOME                   VARCHAR(200)  	 NOT NULL,
       CONTATO                VARCHAR (15)       NOT NULL);
 
CREATE TABLE ENDERECO(
       ID_ENDERECO             INTEGER 	 	NOT NULL	 PRIMARY KEY AUTO_INCREMENT,
       ID_CLIENTE              INTEGER       	NOT NULL,
       CEP                     VARCHAR(8)       NOT NULL,
       NUMERO                  VARCHAR(15)  	NOT NULL,
       COMPLEMENTO             VARCHAR(200)   	NOT NULL,
       RUA                     VARCHAR(200) 	NOT NULL,
       BAIRRO                  VARCHAR(200)	NOT NULL,
       CIDADE                  VARCHAR(100) 	NOT NULL,
       ESTADO                  VARCHAR(100)	NOT NULL);


ALTER TABLE LIVRO ADD CONSTRAINT FK_EDITORA_LIVRO
	FOREIGN KEY(ID_EDITORA) REFERENCES EDITORA(ID_EDITORA);

ALTER TABLE LIVRO ADD CONSTRAINT FK_AUTOR_LIVRO
	FOREIGN KEY(ID_AUTOR) REFERENCES AUTOR(ID_AUTOR);

ALTER TABLE LIVRO ADD CONSTRAINT FK_GENERO_LIVRO
	FOREIGN KEY(ID_GENERO) REFERENCES GENERO(ID_GENERO);

ALTER TABLE ESTOQUE ADD CONSTRAINT FK_LIVRO_ESTOQUE
	FOREIGN KEY(ID_LIVRO) REFERENCES LIVRO(ID_LIVRO);

ALTER TABLE VENDA ADD CONSTRAINT FK_CLIENTE_VENDA
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);

ALTER TABLE VENDA ADD CONSTRAINT FK_VENDEDOR_VENDA
	FOREIGN KEY(ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_CLIENTE_ENDERECO
	FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
